name: Build & Deploy

# Trigger auf Push in main
on:
  push:
    branches:
      - main

# Erforderliche Schreibrechte:
permissions:
  contents: write        # zum Committen neuer Dateien
  pages: write           # zum Veröffentlichen auf GitHub Pages
  id-token: write        # falls Du später OIDC brauchst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Hol’ den Code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # <— ganz wichtig für gh-pages-Push

      # 2) Leg public/ an (falls nicht da)
      - name: Prepare public directory
        run: mkdir -p public

      # 3) Generiere config.js aus dem Secret
      - name: Generate config.js from Secret
        run: |
          cat <<EOF > public/config.js
          // !!! Automatisch erzeugt !!!
          window.firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: 'codegame-dev.firebaseapp.com',
            projectId: 'codegame-dev',
            storageBucket: 'codegame-dev.firebasestorage.app',
            messagingSenderId: '787254922496',
            appId: '1:787254922496:web:e4728c517363197eb7f7e5',
            measurementId: 'G-R3X0TKGNZV'
          };
          EOF

      # 4) Deploy zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
