name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate config.js from Secret
        run: |
          cat <<EOF > public/config.js
          // !!! Diese Datei wird automatisch erzeugt !!!
          window.firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: 'codegame-dev.firebaseapp.com',
            projectId: 'codegame-dev',
            storageBucket: 'codegame-dev.firebasestorage.app',
            messagingSenderId: '787254922496',
            appId: '1:787254922496:web:e4728c517363197eb7f7e5',
            measurementId: 'G-R3X0TKGNZV'
          };
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
